### ISSUE TITLE
NG-20 Fore Landing gear thrusters only one side

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#1066]
The NG-20 Fore Landing gear is a universal (none flip-able) front landing gear with right and left thrusters. It is bugged and only has the thrusters and mist come out of the port side. The starboard side does nothing. This came about after a Starfield update and has not been fixed since. You can read the discussion on it at 
https://www.reddit.com/r/NoSodiumStarfield/comments/1ag3ztd/has_anyone_else_experienced_this_landing_gear_bug/ 

and at 

https://steamcommunity.com/app/1716740/discussions/0/4343229179780852299/

---

## Details 
The NG-20 Fore Landing gear is a landing gear with thrusters designed to be placed at the front of the ship. It is not a flippable item. It has thrusters pointing to the port and the starboard sides. These thrusters fire when taking off/landing and show the the steam mist when the ship is on the ground landed. After one of the Starfield updates (can't remember which one as it's been a while) the Starboard (right) side thrusters were nerfed. Now only the port (left side) thruster fire when taking off/landing or show steam when landed. In-Game Version Shows: 89217928 V1.12.36.0  Steam shows Build ID:14849439

## Game Version
89217928 V1.12.36.0

## Language
English (EN)

## New Game
Yes

## Reproduction Steps
Install the NG-20 Fore Landing gear on any ship. Watch them while taking off or landing. Watch them while landed. Pretty obvious they only fire on one side.

**Comment by Deebz96** [comment]
Seems to be caused by the node in this model being called FX_LandingEngine001, instead of FX_LandingEngine. File corrected with NifSkope.

Credit for finding the fix to this issue goes to: Grizbane

[SFCP_1066.zip](https://github.com/user-attachments/files/16643133/SFCP_1066.zip)

**Comment by ebkarlson404** [comment]
Just downloaded the Shattered Space update and checked the NIF - the bug is still there in the Shattered Space update.
