### ISSUE TITLE
Door inaccessible in City_CY_Runaway01 "Runaway"

### ISSUE THREAD

**Issue by ja231c** [Starfield-Community-Patch/Starfield-Community-Patch#265]
Seems to be a pretty common bug, seeing as searching the internet for it returned quite a lot of results.

At stage 400 it's supposed to unlock the door on the 3rd floor of the Hotel Volii, this can sometimes not happen making it impossible to talk to Natan and continue the quest.
The door alias (NatanDoor) is filled.

This process has 2 steps, one makes the door accessible (using the new SetDoorInaccessible function), this makes the door show [Inaccessible] when hovered over instead of nothing at all, this part works perfectly fine.
Then the door is supposed to be unlocked, however this does not always happen.

No idea why it doesn't work, perhaps there needs to be a delay after calling SetDoorInaccessible before unlocking.

**Comment by Deebz96** [comment]
Have been unable to replicate this one in any playthrough. May have been fixed officially.

**Comment by Constellation-VASCO** [comment]
Still happens as per 1.14.70 in my save. Issue has existed before patch so it likely carried over
